name: build-openlane-sky130
on: [push]
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    env:
      OPENLANE_ROOT: not_really_used
      PDK_ROOT: not_really_used
    steps:
      - name: Checkout subservient
        uses: actions/checkout@v2
        with:
          path: subservient
      - run: echo "EDALIZE_LAUNCHER=${GITHUB_WORKSPACE}/subservient/.github/workflows/openlane_runner.py" >> $GITHUB_ENV
      - run: pip3 install fusesoc
      - run: fusesoc library add serv https://github.com/olofk/serv
      - run: fusesoc library add subservient $GITHUB_WORKSPACE/subservient
      - run: fusesoc run --target=sky130 subservient
